language: python
sudo: true
python:
- '2.7'
install:
- pip install ansible
- ansible-galaxy install -r tests/requirements.yml -p tests/roles
before_script:
- ansible --version
- ansible-playbook --syntax-check ./tests/site.yml -i ./tests/hosts
script:
- ./tests/run
notifications:
  slack:
    secure: vVscBbnkSLdy6gBsxuDX81cbn59p9jd8YADG6QlmyiZ48ipqOTt69mtVVKw/t2JFcoI98FnqFDvjb35TP4JvCiIW5qpq89/2JzpNJoIunUc7cXlA553Wqrg2PdOE3lZhlu10r7KOuKUA7ATCaofqVXT6IsHnJdyTBMk4tY+Urw/Zt+tH1AY4apyWmS366wGVg5AE1jlcrSKDwSMEUC7mf5KxILvb1jzJfXKkw9H8NPrdelV/TDlTzV75EQRE7lG/OyYymujIXZyIW7MwXvrr4+yV0gjH7poaCtCum6FEpdN2jWJ2ZweRl7dgZso+TOvwV45XoiwicjEExR//4ipCZIVv2Y/e5Gm98ixeTwpj5ptVibJsh3fT7GFRQXeZBekFr4vpg5Reni58dlgatBz+3LEflLcbHSOBpfRNd/30U+IoNv0lFQsUAgi4/Du8Kl/8R2UbqKip+KA2EUqEXf3TROMIG09I2DNAVjN07MVzQ+EjU76xMnd1tg6XL30rKcScsnJniwPGfu5hLpwEnXhM4yD7fMUfHOn8dLRHTUQjbIl7Sud4Ym85zMSzpJwVeMw/nGbAt+w6i52qCPELDceVxvzyxs4iLSUpMar/if+ggGlsSr0M0b7ay4Ob8JfUKse1mOfXQ7B0PoSi0vsdLoGQBdhXttwzjOaZ5uZiw32WzTs=
